---
version: '3.1'

services:
  odoo:
    container_name: odoo2
    image: odoo:15
    depends_on:
      - db
    ports:
      - "8073:8073"
    environment:
      - HOST=db2
      - USER=odoo
      - PASSWORD=myodoo
    volumes:
      - ./config:/etc/odoo
    networks:
      - uat-network

  db:
    container_name: db2
    image: postgres:16.3
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
    volumes:
      - /var/lib/docker/volumes/uat-vol/_data:/var/lib/postgresql/data
    networks:
      - uat-network
networks:
  uat-network:
    external: true
