name: Deploy Odoo

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install ssh and sshpass
        run: |
          sudo apt update
          sudo apt install -y ssh sshpass

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install yamllint
        run: sudo apt-get install -y yamllint

      - name: Lint docker-compose YAML files
        run: |
          yamllint ./nginx/docker-compose.yaml
          yamllint ./prod-odoo/docker-compose.yaml
          yamllint ./uat-odoo/docker-compose.yaml

      - name: Aqua Security Trivy
        uses: aquasecurity/trivy-action@0.9.2
        with:
          image-ref: odoo:17
          format: table
          ignore-unfixed: true
          severity: CRITICAL,HIGH
          exit-code: 0

      - name: Add SSH key to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files to server
        run: |
          scp -r ./nginx prod-odoo uat-odoo ubuntu@${{ secrets.HOST }}:/home/ubuntu

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
             echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S curl -fsSL https://get.docker.com | sudo sh
             echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S usermod -aG docker ubuntu
             echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S apt install -y docker-compose-plugin
             echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker network create prod-network || true
             echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker network create uat-network || true
             echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker volume create prod-vol || true
             echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker volume create uat-vol || true
             # echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker compose -f ~/nginx/docker-compose.yml up -d
             # echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker compose -f ~/prod-odoo/docker-compose.yml up -d
             # echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S docker compose -f ~/uat-odoo/docker-compose.yml up -d 
             cd ~/nginx && sudo docker compose up -d
             cd ~/prod-odoo && sudo docker compose up -d
             continue-on-error: true
             cd ~/uat-odoo && sudo mkdir config
             sudo touch ~/uat-odoo/config/odoo.conf
             cd ~/uat-odoo && sudo echo "[options]\nxmlrpc_port = 8073" > odoo.conf 
             cd ~/uat-odoo && sudo docker compose up -d
