name: Deploy Odoo

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install ssh and sshpass
        run: |
          sudo apt update
          sudo apt install -y ssh sshpass

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install yamllint
        run: sudo apt-get install -y yamllint

      - name: Lint docker-compose YAML files
        run: |
          yamllint ./nginx/docker-compose.yml
          yamllint ./prod-odoo/docker-compose.yml
          yamllint ./uat-odoo/docker-compose.yml

      - name: Aqua Security Trivy
        uses: aquasecurity/trivy-action@0.9.2
        with:
          image-ref: odoo:17
          format: table
          ignore-unfixed: true
          severity: CRITICAL,HIGH
          exit-code: 0

      - name: Add SSH key to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files to server
        run: |
          scp -r ./nginx_proxy prod-odoo uat-odoo sqlbak scripts ubuntu@${{ secrets.HOST }}:/home/ubuntu

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            chmod +x ~/scripts/install-docker.sh
            ~/scripts/install-docker.sh

            docker network create prod-network || true
            docker network create uat-network || true
            docker volume create prod-vol || true
            docker volume create uat-vol || true
            
            cd ~/nginx_proxy && docker compose up -d
            cd ~/prod-odoo && docker compose up -d
            cd ~/uat-odoo && docker compose up -d
