name: Deploy Odoo

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install ssh and sshpass
        run: |
          sudo apt update
          sudo apt install -y ssh sshpass

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install yamllint
        run: sudo apt-get install -y yamllint

      - name: Lint docker-compose YAML files
        run: |
          yamllint ./nginx/docker-compose.yaml
          yamllint ./prod-odoo/docker-compose.yaml
          yamllint ./uat-odoo/docker-compose.yaml

      - name: Aqua Security Trivy
        uses: aquasecurity/trivy-action@0.9.2
        with:
          image-ref: odoo:17
          format: table
          ignore-unfixed: true
          severity: CRITICAL,HIGH
          exit-code: 0

      - name: Add SSH key to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files to server
        run: |
          scp -r ./nginx prod-odoo uat-odoo root@${{ secrets.HOST }}:/home/ubuntu

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
             sudo -S curl -fsSL https://get.docker.com | sudo sh
             sudo -S usermod -aG docker ubuntu
             sudo -S apt install -y docker-compose-plugin
             sudo -S docker network create prod-network || true
             sudo -S docker network create uat-network || true
             sudo -S docker volume create prod-vol || true
             sudo -S docker volume create uat-vol || true
             cd /home/ubuntu/uat-odoo && sudo mkdir config
             sudo touch /home/ubuntu/uat-odoo/config/odoo.conf || true
             sudo echo -e "[options]\nxmlrpc_port = 8073"> /home/ubuntu/uat-odoo/config/odoo.conf || true
             cd /home/ubuntu/nginx && sudo docker compose up -d
             cd /home/ubuntu/prod-odoo && sudo docker compose up -d
             cd /home/ubuntu/uat-odoo && sudo docker compose up -d
